strategy:
  matrix:
    windows:
      imageName: 'vs2017-win2016'
#    linux:
#      imageName: 'ubuntu-16.04'
#    mac:
#      imageName: 'macos-10.13'
#    windows:
#      imageName: 'vs2017-win2016'

pool:
  vmImage: $(imageName)

steps:
- bash: |
    curl https://win.rustup.rs/x86_64 > rustup-init.exe
    ./rustup-init.exe -y
    echo "##vso[task.prependpath]$USERPROFILE\.cargo\bin"
  displayName: Install Rust
    
- task: CMake@1
  inputs:
    cmakeArgs: ..
        
- task: CMake@1
  inputs:
    cmakeArgs: --build .
