[package]
name = "cmake-cargo-gen"
version = "0.1.0"
authors = ["Andrew Gaspar <andrew.gaspar@outlook.com>"]

[dependencies]
cargo_metadata = "0.5.1"
clap = { version = "2.31.1", default-features=false }