on: [push, pull_request]
defaults:
  run:
    shell: bash
jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: 
          - windows-latest
          - ubuntu-latest
          - macos-latest
        cmake:
          - 3.12.4
          - 3.17.3
    steps:
      - name: Install CMake
        uses: symbitic/install-cmake@master
        with:
          cmake: ${{matrix.cmake}}
          ninja: 1.10.0
      - name: CMake Version
        run: cmake --version
